<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CategoriesTableSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('categories')->upsert([
            [
                'id' => 1,
                'parent_id' => null,
                'name' => 'Cây Cảnh',
                'slug' => 'cay-canh',
                'description' => null,
                'image' => null,
                'order' => 1,
                'is_active' => 1,
                'metadata' => null,
                'created_at' => '2025-11-25 04:02:52',
                'updated_at' => '2025-11-25 04:02:52',
            ],
            [
                'id' => 2,
                'parent_id' => null,
                'name' => 'Cây Phong Thủy',
                'slug' => 'cay-phong-thuy',
                'description' => null,
                'image' => null,
                'order' => 0,
                'is_active' => 1,
                'metadata' => null,
                'created_at' => '2025-11-25 04:02:52',
                'updated_at' => '2025-11-25 04:02:52',
            ],
            [
                'id' => 3,
                'parent_id' => null,
                'name' => 'Cây Hoa Đẹp',
                'slug' => 'cay-hoa-dep',
                'description' => null,
                'image' => null,
                'order' => 2,
                'is_active' => 1,
                'metadata' => null,
                'created_at' => '2025-11-25 04:02:52',
                'updated_at' => '2025-11-25 04:02:52',
            ],
            [
                'id' => 4,
                'parent_id' => null,
                'name' => 'Sen Đá – Xương Rồng',
                'slug' => 'sen-da-xuong-rong',
                'description' => null,
                'image' => null,
                'order' => 3,
                'is_active' => 1,
                'metadata' => null,
                'created_at' => '2025-11-25 04:02:52',
                'updated_at' => '2025-11-25 04:02:52',
            ],
            [
                'id' => 5,
                'parent_id' => null,
                'name' => 'Chậu Cây – Phụ Kiện',
                'slug' => 'chau-cay-phu-kien',
                'description' => null,
                'image' => null,
                'order' => 4,
                'is_active' => 1,
                'metadata' => null,
                'created_at' => '2025-11-25 04:02:52',
                'updated_at' => '2025-11-25 04:02:52',
            ],
            [
                'id' => 6,
                'parent_id' => 1,
                'name' => 'Cây để bàn',
                'slug' => 'cay-de-ban',
                'description' => null,
                'image' => null,
                'order' => 0,
                'is_active' => 1,
                'metadata' => null,
                'created_at' => '2025-11-25 04:03:08',
                'updated_at' => '2025-11-25 04:03:08',
            ],
            [
                'id' => 7,
                'parent_id' => 1,
                'name' => 'Cây trong nhà',
                'slug' => 'cay-trong-nha',
                'description' => null,
                'image' => null,
                'order' => 0,
                'is_active' => 1,
                'metadata' => null,
                'created_at' => '2025-11-25 04:03:08',
                'updated_at' => '2025-11-25 04:03:08',
            ],
            [
                'id' => 8,
                'parent_id' => 1,
                'name' => 'Cây ngoài trời',
                'slug' => 'cay-ngoai-troi',
                'description' => null,
                'image' => null,
                'order' => 0,
                'is_active' => 1,
                'metadata' => null,
                'created_at' => '2025-11-25 04:03:08',
                'updated_at' => '2025-11-25 04:03:08',
            ],
            [
                'id' => 9,
                'parent_id' => 1,
                'name' => 'Cây mini',
                'slug' => 'cay-mini',
                'description' => null,
                'image' => null,
                'order' => 0,
                'is_active' => 1,
                'metadata' => null,
                'created_at' => '2025-11-25 04:03:08',
                'updated_at' => '2025-11-25 04:03:08',
            ],
            [
                'id' => 10,
                'parent_id' => 1,
                'name' => 'Cây bonsai',
                'slug' => 'cay-bonsai',
                'description' => null,
                'image' => 'cay-bonsai-C99gR4bQ.webp',
                'order' => 0,
                'is_active' => 1,
                'metadata' => null,
                'created_at' => '2025-11-25 04:03:08',
                'updated_at' => '2025-11-30 15:24:36',
            ],
            [
                'id' => 11,
                'parent_id' => 1,
                'name' => 'Cây thủy sinh',
                'slug' => 'cay-thuy-sinh',
                'description' => null,
                'image' => null,
                'order' => 0,
                'is_active' => 1,
                'metadata' => null,
                'created_at' => '2025-11-25 04:03:08',
                'updated_at' => '2025-11-25 04:03:08',
            ],
            [
                'id' => 12,
                'parent_id' => 2,
                'name' => 'Cây mang ý nghĩa tài lộc',
                'slug' => 'cay-y-nghia-tai-loc',
                'description' => null,
                'image' => null,
                'order' => 0,
                'is_active' => 1,
                'metadata' => null,
                'created_at' => '2025-11-25 04:03:08',
                'updated_at' => '2025-11-25 04:03:08',
            ],
            [
                'id' => 13,
                'parent_id' => 2,
                'name' => 'Cây hút tài – chiêu lộc',
                'slug' => 'cay-hut-tai-chieu-loc',
                'description' => null,
                'image' => null,
                'order' => 0,
                'is_active' => 1,
                'metadata' => null,
                'created_at' => '2025-11-25 04:03:08',
                'updated_at' => '2025-11-25 04:03:08',
            ],
            [
                'id' => 14,
                'parent_id' => 2,
                'name' => 'Cây hợp mệnh',
                'slug' => 'cay-hop-menh',
                'description' => null,
                'image' => null,
                'order' => 0,
                'is_active' => 1,
                'metadata' => null,
                'created_at' => '2025-11-25 04:03:08',
                'updated_at' => '2025-11-25 04:03:08',
            ],
            [
                'id' => 15,
                'parent_id' => 2,
                'name' => 'Cây hợp tuổi',
                'slug' => 'cay-hop-tuoi',
                'description' => null,
                'image' => null,
                'order' => 0,
                'is_active' => 1,
                'metadata' => null,
                'created_at' => '2025-11-25 04:03:08',
                'updated_at' => '2025-11-25 04:03:08',
            ],
            [
                'id' => 16,
                'parent_id' => 2,
                'name' => 'Cây để bàn phong thủy',
                'slug' => 'cay-de-ban-phong-thuy',
                'description' => null,
                'image' => null,
                'order' => 0,
                'is_active' => 1,
                'metadata' => null,
                'created_at' => '2025-11-25 04:03:08',
                'updated_at' => '2025-11-25 04:03:08',
            ],
            [
                'id' => 17,
                'parent_id' => 2,
                'name' => 'Cây nội thất phong thủy',
                'slug' => 'cay-noi-that-phong-thuy',
                'description' => null,
                'image' => null,
                'order' => 0,
                'is_active' => 1,
                'metadata' => null,
                'created_at' => '2025-11-25 04:03:08',
                'updated_at' => '2025-11-25 04:03:08',
            ],
            [
                'id' => 18,
                'parent_id' => 14,
                'name' => 'Cây hợp mệnh Kim',
                'slug' => 'cay-hop-menh-kim',
                'description' => null,
                'image' => null,
                'order' => 0,
                'is_active' => 1,
                'metadata' => null,
                'created_at' => '2025-11-25 04:03:45',
                'updated_at' => '2025-11-25 04:03:45',
            ],
            [
                'id' => 19,
                'parent_id' => 14,
                'name' => 'Cây hợp mệnh Mộc',
                'slug' => 'cay-hop-menh-moc',
                'description' => null,
                'image' => null,
                'order' => 0,
                'is_active' => 1,
                'metadata' => null,
                'created_at' => '2025-11-25 04:03:45',
                'updated_at' => '2025-11-25 04:03:45',
            ],
            [
                'id' => 20,
                'parent_id' => 14,
                'name' => 'Cây hợp mệnh Thủy',
                'slug' => 'cay-hop-menh-thuy',
                'description' => null,
                'image' => null,
                'order' => 0,
                'is_active' => 1,
                'metadata' => null,
                'created_at' => '2025-11-25 04:03:45',
                'updated_at' => '2025-11-25 04:03:45',
            ],
            [
                'id' => 21,
                'parent_id' => 14,
                'name' => 'Cây hợp mệnh Hỏa',
                'slug' => 'cay-hop-menh-hoa',
                'description' => null,
                'image' => null,
                'order' => 0,
                'is_active' => 1,
                'metadata' => null,
                'created_at' => '2025-11-25 04:03:45',
                'updated_at' => '2025-11-25 04:03:45',
            ],
            [
                'id' => 22,
                'parent_id' => 14,
                'name' => 'Cây hợp mệnh Thổ',
                'slug' => 'cay-hop-menh-tho',
                'description' => null,
                'image' => null,
                'order' => 0,
                'is_active' => 1,
                'metadata' => null,
                'created_at' => '2025-11-25 04:03:45',
                'updated_at' => '2025-11-25 04:03:45',
            ],
            [
                'id' => 23,
                'parent_id' => 3,
                'name' => 'Hoa để bàn',
                'slug' => 'hoa-de-ban',
                'description' => null,
                'image' => null,
                'order' => 0,
                'is_active' => 1,
                'metadata' => null,
                'created_at' => '2025-11-25 04:03:55',
                'updated_at' => '2025-11-25 04:03:55',
            ],
            [
                'id' => 24,
                'parent_id' => 3,
                'name' => 'Hoa trong nhà',
                'slug' => 'hoa-trong-nha',
                'description' => null,
                'image' => null,
                'order' => 0,
                'is_active' => 1,
                'metadata' => null,
                'created_at' => '2025-11-25 04:03:55',
                'updated_at' => '2025-11-25 04:03:55',
            ],
            [
                'id' => 25,
                'parent_id' => 3,
                'name' => 'Hoa ngoài trời',
                'slug' => 'hoa-ngoai-troi',
                'description' => null,
                'image' => null,
                'order' => 0,
                'is_active' => 1,
                'metadata' => null,
                'created_at' => '2025-11-25 04:03:55',
                'updated_at' => '2025-11-25 04:03:55',
            ],
            [
                'id' => 26,
                'parent_id' => 3,
                'name' => 'Hoa phong thủy',
                'slug' => 'hoa-phong-thuy',
                'description' => null,
                'image' => null,
                'order' => 0,
                'is_active' => 1,
                'metadata' => null,
                'created_at' => '2025-11-25 04:03:55',
                'updated_at' => '2025-11-25 04:03:55',
            ],
            [
                'id' => 27,
                'parent_id' => 3,
                'name' => 'Hoa leo – hoa dây',
                'slug' => 'hoa-leo',
                'description' => null,
                'image' => null,
                'order' => 0,
                'is_active' => 1,
                'metadata' => null,
                'created_at' => '2025-11-25 04:03:55',
                'updated_at' => '2025-11-25 04:03:55',
            ],
            [
                'id' => 28,
                'parent_id' => 4,
                'name' => 'Sen đá các loại',
                'slug' => 'sen-da-cac-loai',
                'description' => null,
                'image' => null,
                'order' => 0,
                'is_active' => 1,
                'metadata' => null,
                'created_at' => '2025-11-25 04:03:55',
                'updated_at' => '2025-11-25 04:03:55',
            ],
            [
                'id' => 29,
                'parent_id' => 4,
                'name' => 'Xương rồng mini',
                'slug' => 'xuong-rong-mini',
                'description' => null,
                'image' => null,
                'order' => 0,
                'is_active' => 1,
                'metadata' => null,
                'created_at' => '2025-11-25 04:03:55',
                'updated_at' => '2025-11-25 04:03:55',
            ],
            [
                'id' => 30,
                'parent_id' => 4,
                'name' => 'Combo sen đá',
                'slug' => 'combo-sen-da',
                'description' => null,
                'image' => null,
                'order' => 0,
                'is_active' => 1,
                'metadata' => null,
                'created_at' => '2025-11-25 04:03:55',
                'updated_at' => '2025-11-25 04:03:55',
            ],
            [
                'id' => 31,
                'parent_id' => 5,
                'name' => 'Chậu cây',
                'slug' => 'chau-cay',
                'description' => null,
                'image' => null,
                'order' => 0,
                'is_active' => 1,
                'metadata' => null,
                'created_at' => '2025-11-25 04:03:55',
                'updated_at' => '2025-11-25 04:03:55',
            ],
            [
                'id' => 32,
                'parent_id' => 5,
                'name' => 'Đất – giá thể',
                'slug' => 'dat-gia-the',
                'description' => null,
                'image' => null,
                'order' => 0,
                'is_active' => 1,
                'metadata' => null,
                'created_at' => '2025-11-25 04:03:55',
                'updated_at' => '2025-11-25 04:03:55',
            ],
            [
                'id' => 33,
                'parent_id' => 5,
                'name' => 'Dụng cụ làm vườn',
                'slug' => 'dung-cu-lam-vuon',
                'description' => null,
                'image' => null,
                'order' => 0,
                'is_active' => 1,
                'metadata' => null,
                'created_at' => '2025-11-25 04:03:55',
                'updated_at' => '2025-11-25 04:03:55',
            ],
            [
                'id' => 34,
                'parent_id' => 5,
                'name' => 'Bình tưới – phụ kiện',
                'slug' => 'binh-tuoi-phu-kien',
                'description' => null,
                'image' => null,
                'order' => 0,
                'is_active' => 1,
                'metadata' => null,
                'created_at' => '2025-11-25 04:03:55',
                'updated_at' => '2025-11-25 04:03:55',
            ],
        ], ['id']);
    }
}
