<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SettingsTableSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('settings')->upsert([
            [
                'id' => 1,
                'key' => 'site_name',
                'value' => 'THẾ GIỚI CÂY XANH XWORLD',
                'type' => 'text',
                'group' => 'general',
                'label' => '',
                'description' => null,
                'is_public' => 1,
                'created_at' => '2025-06-10 16:10:59',
                'updated_at' => '2025-06-10 16:10:59',
            ],
            [
                'id' => 2,
                'key' => 'site_description',
                'value' => 'THẾ GIỚI CÂY XANH XWORLD – cây phong thủy, cây để bàn, cây lọc không khí, chậu cảnh đẹp. Decor không gian sống xanh – đẹp – bền. Giao cây tận nơi.',
                'type' => 'text',
                'group' => 'general',
                'label' => 'Mô tả SEO',
                'description' => null,
                'is_public' => 1,
                'created_at' => '2025-06-10 16:10:59',
                'updated_at' => '2025-12-03 08:46:31',
            ],
            [
                'id' => 3,
                'key' => 'site_logo',
                'value' => 'logo-xanhworld.vn.svg',
                'type' => 'image',
                'group' => 'general',
                'label' => 'Ảnh Logo',
                'description' => null,
                'is_public' => 1,
                'created_at' => '2025-06-10 16:10:59',
                'updated_at' => '2025-09-09 19:40:05',
            ],
            [
                'id' => 4,
                'key' => 'site_announcement',
                'value' => 'MIỄN PHÍ VẬN CHUYỂN...',
                'type' => 'text',
                'group' => 'general',
                'label' => '',
                'description' => null,
                'is_public' => 1,
                'created_at' => '2025-06-10 16:10:59',
                'updated_at' => '2025-06-10 16:10:59',
            ],
            [
                'id' => 5,
                'key' => 'site_favicon',
                'value' => 'favicon-xanhworld.vn.svg',
                'type' => 'image',
                'group' => 'general',
                'label' => 'Favicon chính',
                'description' => null,
                'is_public' => 1,
                'created_at' => '2025-06-10 16:10:59',
                'updated_at' => '2025-09-15 18:03:08',
            ],
            [
                'id' => 6,
                'key' => 'contact_email',
                'value' => 'xanhworldvietnam@gmail.com',
                'type' => 'email',
                'group' => 'general',
                'label' => 'Email hỗ trợ',
                'description' => null,
                'is_public' => 1,
                'created_at' => '2025-06-10 16:10:59',
                'updated_at' => '2025-09-09 20:00:38',
            ],
            [
                'id' => 7,
                'key' => 'contact_phone',
                'value' => '0827786198',
                'type' => 'text',
                'group' => 'general',
                'label' => 'Số điện thoại Đức Nobi 💖',
                'description' => null,
                'is_public' => 1,
                'created_at' => '2025-06-10 16:10:59',
                'updated_at' => '2025-09-09 20:12:31',
            ],
            [
                'id' => 8,
                'key' => 'contact_address',
                'value' => 'Xóm 3 - Xã Hà Đông - Thành Phố Hải Phòng',
                'type' => 'text',
                'group' => 'general',
                'label' => 'Địa chỉ bán hàng',
                'description' => null,
                'is_public' => 1,
                'created_at' => '2025-06-10 16:10:59',
                'updated_at' => '2025-12-03 09:13:17',
            ],
            [
                'id' => 9,
                'key' => 'seo_keywords',
                'value' => 'cây xanh, cây cảnh, cây văn phòng, cây phong thủy, cây nội thất, cây để bàn, cây trang trí, chậu cây cảnh, chậu xi măng, phụ kiện decor, setup góc làm việc, setup ban công, cây cảnh mini, cây cảnh để bàn, cây cảnh trong nhà, cây lọc không khí, cây hợp mệnh, cây thủy sinh, shop cây cảnh, xanhworld, xanh world',
                'type' => 'text',
                'group' => 'general',
                'label' => 'Keywords chính - Trang chủ',
                'description' => null,
                'is_public' => 1,
                'created_at' => '2025-06-10 16:10:59',
                'updated_at' => '2025-12-03 08:44:27',
            ],
            [
                'id' => 10,
                'key' => 'seo_author',
                'value' => 'Nguyễn Minh Đức (Đức Nobi)',
                'type' => 'text',
                'group' => 'general',
                'label' => '',
                'description' => null,
                'is_public' => 1,
                'created_at' => '2025-06-10 16:10:59',
                'updated_at' => '2025-06-10 16:10:59',
            ],
            [
                'id' => 11,
                'key' => 'facebook_link',
                'value' => 'https://www.facebook.com/ducnobi2004',
                'type' => 'url',
                'group' => 'general',
                'label' => 'Facebook Đức Nobi',
                'description' => null,
                'is_public' => 1,
                'created_at' => '2025-06-10 16:10:59',
                'updated_at' => '2025-09-09 19:51:01',
            ],
            [
                'id' => 12,
                'key' => 'twitter_link',
                'value' => 'https://twitter.com/',
                'type' => 'text',
                'group' => 'general',
                'label' => '',
                'description' => null,
                'is_public' => 1,
                'created_at' => '2025-06-10 16:10:59',
                'updated_at' => '2025-06-10 16:10:59',
            ],
            [
                'id' => 13,
                'key' => 'google_analytics',
                'value' => '',
                'type' => 'text',
                'group' => 'general',
                'label' => 'Google Analytics',
                'description' => null,
                'is_public' => 1,
                'created_at' => '2025-06-10 16:10:59',
                'updated_at' => '2025-12-03 09:05:31',
            ],
            [
                'id' => 14,
                'key' => 'enable_registration',
                'value' => 'true',
                'type' => 'text',
                'group' => 'general',
                'label' => '',
                'description' => null,
                'is_public' => 1,
                'created_at' => '2025-06-10 16:10:59',
                'updated_at' => '2025-06-10 16:10:59',
            ],
            [
                'id' => 15,
                'key' => 'enable_comments',
                'value' => 'true',
                'type' => 'text',
                'group' => 'general',
                'label' => '',
                'description' => null,
                'is_public' => 1,
                'created_at' => '2025-06-10 16:10:59',
                'updated_at' => '2025-06-10 16:10:59',
            ],
            [
                'id' => 16,
                'key' => 'enable_newsletter',
                'value' => 'true',
                'type' => 'text',
                'group' => 'general',
                'label' => '',
                'description' => null,
                'is_public' => 1,
                'created_at' => '2025-06-10 16:10:59',
                'updated_at' => '2025-06-10 16:10:59',
            ],
            [
                'id' => 17,
                'key' => 'site_timezone',
                'value' => 'Asia/Ho_Chi_Minh',
                'type' => 'text',
                'group' => 'general',
                'label' => '',
                'description' => null,
                'is_public' => 1,
                'created_at' => '2025-06-10 16:10:59',
                'updated_at' => '2025-06-10 16:10:59',
            ],
            [
                'id' => 18,
                'key' => 'site_language',
                'value' => 'vi',
                'type' => 'text',
                'group' => 'general',
                'label' => '',
                'description' => null,
                'is_public' => 1,
                'created_at' => '2025-06-10 16:10:59',
                'updated_at' => '2025-06-10 16:10:59',
            ],
            [
                'id' => 19,
                'key' => 'enable_ssl',
                'value' => 'true',
                'type' => 'text',
                'group' => 'general',
                'label' => '',
                'description' => null,
                'is_public' => 1,
                'created_at' => '2025-06-10 16:10:59',
                'updated_at' => '2025-06-10 16:10:59',
            ],
            [
                'id' => 20,
                'key' => 'maintenance_mode',
                'value' => '0',
                'type' => 'boolean',
                'group' => 'general',
                'label' => 'Chế độ bảo trì',
                'description' => null,
                'is_public' => 1,
                'created_at' => '2025-06-10 16:10:59',
                'updated_at' => '2025-09-09 20:07:44',
            ],
            [
                'id' => 21,
                'key' => 'copyright',
                'value' => 'Copyright &copy; {{ ((2025 != now()->year & 2025 < now()->year) ? \'2025 - \' : \'\'). now()->year }} <a style=\"color: green;\" href=\"{{ $settings->site_url }}\">{{ $settings->site_name }}</a>. All Rights Reserved.',
                'type' => 'textarea',
                'group' => 'general',
                'label' => 'Copyright Footer',
                'description' => null,
                'is_public' => 1,
                'created_at' => '2025-06-10 16:10:59',
                'updated_at' => '2025-09-09 20:09:08',
            ],
            [
                'id' => 22,
                'key' => 'contact_form_recipient',
                'value' => 'xanhworldvietnam@gmail.com',
                'type' => 'email',
                'group' => 'general',
                'label' => 'Email nhận thông tin',
                'description' => null,
                'is_public' => 1,
                'created_at' => '2025-06-10 16:10:59',
                'updated_at' => '2025-12-03 08:55:55',
            ],
            [
                'id' => 23,
                'key' => 'allow_file_uploads',
                'value' => '1',
                'type' => 'boolean',
                'group' => 'general',
                'label' => 'Cho phép tải lên FILE',
                'description' => 'Cho phép tải lên FILE',
                'is_public' => 1,
                'created_at' => '2025-06-10 16:10:59',
                'updated_at' => '2025-09-09 19:43:04',
            ],
            [
                'id' => 24,
                'key' => 'site_url',
                'value' => 'http://127.0.0.1:8000',
                'type' => 'url',
                'group' => 'general',
                'label' => 'Domain',
                'description' => null,
                'is_public' => 1,
                'created_at' => '2025-06-10 16:10:59',
                'updated_at' => '2025-09-09 19:54:44',
            ],
            [
                'id' => 25,
                'key' => 'site_slug',
                'value' => '/',
                'type' => 'text',
                'group' => 'general',
                'label' => '',
                'description' => null,
                'is_public' => 1,
                'created_at' => '2025-06-10 16:10:59',
                'updated_at' => '2025-06-10 16:10:59',
            ],
            [
                'id' => 26,
                'key' => 'site_title',
                'value' => 'NOBI FASHION – Shop Quần Áo Nam Nữ Đẹp, Mix & Match Chuẩn Gu',
                'type' => 'text',
                'group' => 'general',
                'label' => 'Meta title - Trang chủ',
                'description' => null,
                'is_public' => 1,
                'created_at' => '2025-06-10 16:10:59',
                'updated_at' => '2025-09-09 20:05:42',
            ],
            [
                'id' => 27,
                'key' => 'google_search_console',
                'value' => '',
                'type' => 'text',
                'group' => 'general',
                'label' => 'Google Search Console',
                'description' => null,
                'is_public' => 1,
                'created_at' => '2025-06-10 16:10:59',
                'updated_at' => '2025-12-03 09:05:49',
            ],
            [
                'id' => 28,
                'key' => 'instagram_link',
                'value' => 'https://www.facebook.com/ducnobi2004',
                'type' => 'text',
                'group' => 'general',
                'label' => '',
                'description' => null,
                'is_public' => 1,
                'created_at' => '2025-06-10 16:10:59',
                'updated_at' => '2025-06-10 16:10:59',
            ],
            [
                'id' => 29,
                'key' => 'dmca',
                'value' => '',
                'type' => 'text',
                'group' => 'general',
                'label' => 'Chống sao chép',
                'description' => null,
                'is_public' => 1,
                'created_at' => '2025-06-10 16:10:59',
                'updated_at' => '2025-12-03 09:04:00',
            ],
            [
                'id' => 30,
                'key' => 'dmca_logo',
                'value' => 'https://images.dmca.com/Badges/DMCA_logo-grn-btn120w.png?ID=2fe593a9-a802-4d1b-9501-c3654a4771ed',
                'type' => 'text',
                'group' => 'general',
                'label' => 'Chống sao chép (IMG)',
                'description' => null,
                'is_public' => 1,
                'created_at' => '2025-06-10 16:10:59',
                'updated_at' => '2025-12-03 09:05:06',
            ],
            [
                'id' => 31,
                'key' => 'bo_cong_thuong',
                'value' => 'http://online.gov.vn/Home/WebDetails/137357',
                'type' => 'image',
                'group' => 'general',
                'label' => 'Ảnh bộ công thương',
                'description' => 'setting-bo_cong_thuong-1757497818.webp',
                'is_public' => 1,
                'created_at' => '2025-06-10 16:10:59',
                'updated_at' => '2025-09-09 19:50:18',
            ],
            [
                'id' => 32,
                'key' => 'contact_zalo',
                'value' => '0398951396',
                'type' => 'text',
                'group' => 'general',
                'label' => 'Zalo Đức Nobi 💖',
                'description' => null,
                'is_public' => 1,
                'created_at' => '2025-06-10 16:10:59',
                'updated_at' => '2025-09-09 20:11:52',
            ],
            [
                'id' => 33,
                'key' => 'telegram_link',
                'value' => 'https://discord.gg/nobifashion',
                'type' => 'text',
                'group' => 'general',
                'label' => '',
                'description' => null,
                'is_public' => 1,
                'created_at' => '2025-06-10 16:10:59',
                'updated_at' => '2025-06-10 16:10:59',
            ],
            [
                'id' => 34,
                'key' => 'discord_link',
                'value' => 'https://discord.gg/nobifashion',
                'type' => 'text',
                'group' => 'general',
                'label' => '',
                'description' => null,
                'is_public' => 1,
                'created_at' => '2025-06-10 16:10:59',
                'updated_at' => '2025-06-10 16:10:59',
            ],
            [
                'id' => 35,
                'key' => 'site_image',
                'value' => '',
                'type' => 'text',
                'group' => 'general',
                'label' => '',
                'description' => null,
                'is_public' => 1,
                'created_at' => '2025-06-10 16:10:59',
                'updated_at' => '2025-06-10 16:10:59',
            ],
            [
                'id' => 36,
                'key' => 'google_tag_header',
                'value' => "<!-- Google Tag Manager -->\n<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':\nnew Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],\nj=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=\n'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);\n})(window,document,'script','dataLayer','GTM-KPTC863L');</script>\n<!-- End Google Tag Manager -->\n<!-- Google tag (gtag.js) -->\n<script async src=\"https://www.googletagmanager.com/gtag/js?id=AW-17013569193\"></script>\n<script>\n  window.dataLayer = window.dataLayer || [];\n  function gtag(){dataLayer.push(arguments);}\n  gtag('js', new Date());\n\n  gtag('config', 'AW-17013569193');\n</script>\n<!-- Event snippet for Lượt xem trang conversion page -->\n<script>\n  gtag('event', 'conversion', {\n      'send_to': 'AW-17013569193/3VCDCPK1zrkaEKnt2bA_',\n      'value': 1.0,\n      'currency': 'VND'\n  });\n</script>",
                'type' => 'text',
                'group' => 'general',
                'label' => 'Google Tag Header',
                'description' => null,
                'is_public' => 1,
                'created_at' => '2025-06-10 16:10:59',
                'updated_at' => '2025-12-03 09:06:05',
            ],
            [
                'id' => 37,
                'key' => 'google_tag_body',
                'value' => '',
                'type' => 'text',
                'group' => 'general',
                'label' => 'Thẻ Google Body',
                'description' => null,
                'is_public' => 1,
                'created_at' => '2025-06-10 16:10:59',
                'updated_at' => '2025-12-03 09:04:34',
            ],
            [
                'id' => 38,
                'key' => 'site_pinterest',
                'value' => '',
                'type' => 'text',
                'group' => 'general',
                'label' => '',
                'description' => null,
                'is_public' => 1,
                'created_at' => '2025-06-10 16:10:59',
                'updated_at' => null,
            ],
            [
                'id' => 39,
                'key' => 'site_banner',
                'value' => 'banner.webp',
                'type' => 'text',
                'group' => 'general',
                'label' => '',
                'description' => null,
                'is_public' => 1,
                'created_at' => '2025-06-10 16:10:59',
                'updated_at' => null,
            ],
            [
                'id' => 40,
                'key' => 'url_banner',
                'value' => 'setting-url_banner-1757498296.png',
                'type' => 'image',
                'group' => 'general',
                'label' => 'Banner chính',
                'description' => null,
                'is_public' => 1,
                'created_at' => '2025-06-10 16:10:59',
                'updated_at' => '2025-09-09 19:58:16',
            ],
            [
                'id' => 41,
                'key' => 'bing_tag_header',
                'value' => '',
                'type' => 'text',
                'group' => 'general',
                'label' => '',
                'description' => null,
                'is_public' => 1,
                'created_at' => '2025-06-10 16:10:59',
                'updated_at' => null,
            ],
            [
                'id' => 43,
                'key' => 'postalCode',
                'value' => '180000',
                'type' => 'text',
                'group' => 'general',
                'label' => '',
                'description' => null,
                'is_public' => 1,
                'created_at' => '2025-06-11 00:31:16',
                'updated_at' => null,
            ],
            [
                'id' => 44,
                'key' => 'subname',
                'value' => 'XWORLD',
                'type' => 'text',
                'group' => 'general',
                'label' => '',
                'description' => null,
                'is_public' => 1,
                'created_at' => '2025-06-16 00:23:46',
                'updated_at' => null,
            ],
            [
                'id' => 45,
                'key' => 'city',
                'value' => 'Hải Phòng',
                'type' => 'text',
                'group' => 'general',
                'label' => 'Thành phố',
                'description' => null,
                'is_public' => 1,
                'created_at' => '2025-07-16 02:46:33',
                'updated_at' => '2025-12-03 08:56:10',
            ],
            [
                'id' => 46,
                'key' => 'district',
                'value' => 'Hải Phòng',
                'type' => 'text',
                'group' => 'general',
                'label' => 'Quận/Huyện',
                'description' => null,
                'is_public' => 1,
                'created_at' => '2025-07-16 02:47:28',
                'updated_at' => '2025-12-03 08:57:02',
            ],
            [
                'id' => 47,
                'key' => 'ward',
                'value' => 'PHƯỜNG LÃM HÀ',
                'type' => 'text',
                'group' => 'general',
                'label' => '',
                'description' => null,
                'is_public' => 1,
                'created_at' => '2025-07-16 02:47:28',
                'updated_at' => null,
            ],
            [
                'id' => 48,
                'key' => 'detail_address',
                'value' => 'Xóm 3 - Xã Hà Đông - Thành Phố Hải Phòng',
                'type' => 'text',
                'group' => 'general',
                'label' => 'Địa chỉ bán hàng',
                'description' => null,
                'is_public' => 1,
                'created_at' => '2025-07-16 02:47:28',
                'updated_at' => '2025-12-03 08:55:15',
            ],
            [
                'id' => 49,
                'key' => 'latitude',
                'value' => '20.83943',
                'type' => 'text',
                'group' => 'general',
                'label' => '',
                'description' => null,
                'is_public' => 1,
                'created_at' => '2025-07-20 01:55:34',
                'updated_at' => null,
            ],
            [
                'id' => 50,
                'key' => 'longitude',
                'value' => '106.65338',
                'type' => 'text',
                'group' => 'general',
                'label' => '',
                'description' => null,
                'is_public' => 1,
                'created_at' => '2025-07-20 01:55:34',
                'updated_at' => null,
            ],
            [
                'id' => 51,
                'key' => 'enable_cart',
                'value' => 'true',
                'type' => 'text',
                'group' => 'general',
                'label' => '',
                'description' => null,
                'is_public' => 1,
                'created_at' => '2025-07-21 13:54:49',
                'updated_at' => null,
            ],
            [
                'id' => 52,
                'key' => 'enable_order',
                'value' => 'true',
                'type' => 'text',
                'group' => 'general',
                'label' => '',
                'description' => null,
                'is_public' => 1,
                'created_at' => '2025-07-21 13:54:49',
                'updated_at' => null,
            ],
            [
                'id' => 53,
                'key' => 'enable_payment',
                'value' => 'true',
                'type' => 'text',
                'group' => 'general',
                'label' => '',
                'description' => null,
                'is_public' => 1,
                'created_at' => '2025-07-21 13:57:43',
                'updated_at' => null,
            ],
            [
                'id' => 54,
                'key' => 'is_demo',
                'value' => 'true',
                'type' => 'boolean',
                'group' => 'general',
                'label' => '',
                'description' => null,
                'is_public' => 1,
                'created_at' => '2025-07-21 13:57:43',
                'updated_at' => null,
            ],
            [
                'id' => 55,
                'key' => 'site_tax_code',
                'value' => '030204013643',
                'type' => 'string',
                'group' => 'general',
                'label' => 'Mã số thuế',
                'description' => null,
                'is_public' => 1,
                'created_at' => '2025-10-31 00:15:00',
                'updated_at' => '2025-11-17 00:45:39',
            ],
            [
                'id' => 56,
                'key' => 'source_map',
                'value' => 'https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d15676.49041047659!2d106.688084!3d10.780834!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x31752f2bc3a8979f%3A0xe5a3028117c2f383!2sHo%20Chi%20Minh%20City!5e0!3m2!1svi!2s!4v1764171111111!5m2!1svi!2s',
                'type' => 'string',
                'group' => 'general',
                'label' => 'Map XWORLD',
                'description' => null,
                'is_public' => 1,
                'created_at' => '2025-11-28 12:13:35',
                'updated_at' => '2025-12-02 02:56:41',
            ],
        ], ['id']);
    }
}


